[debug]
address = "0.0.0.0"
port = 8080
secret_key = "+wNOPjPWkzhibIMPDHf089lHxxXjSzFH6ENlcAf+dyA="

[release]
address = "0.0.0.0"
port = 8080
secret_key = "+wNOPjPWkzhibIMPDHf089lHxxXjSzFH6ENlcAf+dyA="
